name: Arduino CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: test compile
      uses: arduino/compile-sketches@v1
      with:
        fqbn: "arduino:avr:uno"
